"""
State module: Backward compatibility re-export from application/state.

This module provides a drop-in replacement for the old in-memory state system.
All functions maintain the same API but now persist to SQLite database.

On startup, automatically migrates data from legacy data/user_settings.json.
"""

# Backward compatibility: re-export from application layer
from application.state import (
    FREE_USES_LIMIT,
    active_tasks,
    add_to_history,
    can_use_shared_credentials,
    cleanup_yt_cache,
    clear_history,
    clear_history_async,
    clear_user_setting,
    clear_user_setting_async,
    clear_user_settings_section,
    clear_user_settings_section_async,
    delete_oauth_token_async,
    get_free_uses,
    get_free_uses_async,
    get_history,
    get_history_async,
    get_language,
    get_mode,
    get_oauth_token_async,
    get_or_create_user,
    get_user_setting,
    get_user_setting_async,
    get_user_setting_json,
    get_user_setting_json_async,
    groq_limits,
    increment_free_uses,
    increment_free_uses_async,
    initialize_state,
    load_user_settings,
    migrate_legacy_data,
    set_free_uses,
    set_free_uses_async,
    set_language,
    set_mode,
    set_oauth_token_async,
    set_user_setting,
    set_user_setting_async,
    set_user_setting_json,
    set_user_setting_json_async,
    shutdown_state,
    update_groq_limits,
    user_gdocs,
    user_modes,
    yt_transcripts,
)

# Explicit re-exports for pylint and static analysis
__all__ = [
    "FREE_USES_LIMIT",
    "active_tasks",
    "add_to_history",
    "can_use_shared_credentials",
    "clear_history",
    "clear_history_async",
    "clear_user_setting",
    "clear_user_settings_section",
    "clear_user_settings_section_async",
    "clear_user_setting_async",
    "cleanup_yt_cache",
    "delete_oauth_token_async",
    "get_free_uses",
    "get_free_uses_async",
    "get_history",
    "get_history_async",
    "get_language",
    "get_mode",
    "get_oauth_token_async",
    "get_or_create_user",
    "get_user_setting",
    "get_user_setting_async",
    "get_user_setting_json",
    "get_user_setting_json_async",
    "groq_limits",
    "increment_free_uses",
    "increment_free_uses_async",
    "initialize_state",
    "load_user_settings",
    "migrate_legacy_data",
    "set_free_uses",
    "set_free_uses_async",
    "set_language",
    "set_mode",
    "set_oauth_token_async",
    "set_user_setting",
    "set_user_setting_async",
    "set_user_setting_json",
    "set_user_setting_json_async",
    "shutdown_state",
    "update_groq_limits",
    "user_gdocs",
    "user_modes",
    "yt_transcripts",
]
